# Site settings
title: Epístolas de Zenón
email: Epistolas-de-Zenon@protonmail.com
url: https://example.github.io
description: "Proyecto de Think Tank anarquista. Perseguimos nuevos horizontes de libertad."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Epístolas de Zenón

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: paypal
    url: https://paypal.me/kaththom?locale.x=es_XC
  - title: paypal
    url: 
# Build settings
markdown: kramdown
permalink: pretty
